SELECT
  click_date,
  account_id,
  campaign_id,
  asset_group_id,
  ad_network_type,
  metric_basis,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  cohort_day,
  is_window_rung,
  cohort_label,
  window_days,
  window_provenance,
  provenance,
  unavailable_reason,
  maturity,
  observed_through,
  SUM(click_day_cost) AS click_day_cost,
  SUM(cohorted_conversions) AS cohorted_conversions,
  SUM(cohorted_value) AS cohorted_value,
  SUM(unknown_lag_conversions) AS unknown_lag_conversions,
  SUM(unknown_lag_value) AS unknown_lag_value,
  SUM(stale_cell_count) AS stale_cell_count,
  SAFE_DIVIDE(SUM(click_day_cost),
    NULLIF(SUM(cohorted_conversions), 0)) AS cohort_cpa,
  SAFE_DIVIDE(SUM(cohorted_value),
    NULLIF(SUM(click_day_cost), 0)) AS cohort_roas
FROM `{{ project }}.{{ marts_dataset }}.mart_cohort_asset_group`
WHERE click_day_cost IS NOT NULL
GROUP BY click_date, account_id, campaign_id, asset_group_id,
  ad_network_type, metric_basis, conversion_action_id,
  conversion_action_resource_name, conversion_action_name, cohort_day,
  is_window_rung, cohort_label, window_days, window_provenance, provenance,
  unavailable_reason, maturity, observed_through
