SELECT
  date,
  account_id,
  campaign_id,
  campaign_name,
  campaign_status,
  metric_basis,
  ad_network_type,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  currency_code,
  attribute_provenance,
  SUM(network_impressions) AS network_impressions,
  SUM(network_clicks) AS network_clicks,
  SUM(network_cost) AS network_cost,
  SUM(network_conversions) AS network_conversions,
  SUM(network_conversions_value) AS network_conversions_value,
  SUM(network_all_conversions) AS network_all_conversions,
  SUM(network_all_conversions_value) AS network_all_conversions_value,
  SUM(action_conversions) AS action_conversions,
  SUM(action_conversions_value) AS action_conversions_value,
  SUM(action_all_conversions) AS action_all_conversions,
  SUM(action_all_conversions_value) AS action_all_conversions_value,
  SAFE_DIVIDE(SUM(network_clicks), NULLIF(SUM(network_impressions), 0)) AS ctr,
  SAFE_DIVIDE(SUM(network_cost), NULLIF(SUM(network_conversions), 0)) AS cpa,
  SAFE_DIVIDE(SUM(network_conversions_value), NULLIF(SUM(network_cost), 0)) AS roas
FROM `{{ project }}.{{ marts_dataset }}.mart_performance_campaign`
GROUP BY date, account_id, campaign_id, campaign_name, campaign_status,
  metric_basis, ad_network_type, conversion_action_id,
  conversion_action_resource_name, conversion_action_name, currency_code,
  attribute_provenance
