SELECT
  CAST(NULL AS DATE) AS snapshot_date,
  CAST(NULL AS INT64) AS account_id,
  CAST(NULL AS INT64) AS campaign_id,
  CAST(NULL AS STRING) AS campaign_name,
  CAST(NULL AS STRING) AS status,
  CAST(NULL AS STRING) AS primary_status,
  CAST(NULL AS ARRAY<STRING>) AS primary_status_reasons,
  CAST(NULL AS STRING) AS advertising_channel_type,
  CAST(NULL AS ARRAY<STRUCT<asset_automation_type STRING, asset_automation_status STRING>>) AS asset_automation_settings,
  CAST(NULL AS STRING) AS positive_geo_target_type,
  CAST(NULL AS STRING) AS negative_geo_target_type,
  CAST(NULL AS DATETIME) AS start_date_time,
  CAST(NULL AS DATETIME) AS end_date_time,
  CAST(NULL AS INT64) AS budget_id,
  CAST(NULL AS NUMERIC) AS budget_amount,
  CAST(NULL AS BOOL) AS budget_explicitly_shared,
  CAST(NULL AS STRING) AS budget_period,
  CAST(NULL AS BOOL) AS url_expansion_opt_out,
  CAST(NULL AS DATE) AS first_seen_date,
  CAST(NULL AS DATE) AS last_seen_date,
  CAST(NULL AS BOOL) AS inferred_removed,
  CAST(NULL AS STRING) AS attribute_provenance,
  CAST(NULL AS STRING) AS run_id
LIMIT 0
