SELECT
  CAST(NULL AS DATE) AS snapshot_date,
  CAST(NULL AS INT64) AS account_id,
  CAST(NULL AS INT64) AS campaign_id,
  CAST(NULL AS INT64) AS asset_group_id,
  CAST(NULL AS INT64) AS asset_id,
  CAST(NULL AS STRING) AS field_type,
  CAST(NULL AS STRING) AS status,
  CAST(NULL AS STRING) AS primary_status,
  CAST(NULL AS ARRAY<STRING>) AS primary_status_reasons,
  CAST(NULL AS STRING) AS source,
  CAST(NULL AS STRING) AS asset_name,
  CAST(NULL AS STRING) AS asset_type,
  CAST(NULL AS STRING) AS orientation,
  CAST(NULL AS STRING) AS text,
  CAST(NULL AS STRING) AS image_url,
  CAST(NULL AS INT64) AS image_height_pixels,
  CAST(NULL AS INT64) AS image_width_pixels,
  CAST(NULL AS STRING) AS video_id,
  CAST(NULL AS STRING) AS video_title,
  CAST(NULL AS DATE) AS first_seen_date,
  CAST(NULL AS DATE) AS last_seen_date,
  CAST(NULL AS BOOL) AS inferred_removed,
  CAST(NULL AS STRING) AS attribute_provenance,
  CAST(NULL AS STRING) AS run_id
LIMIT 0
