SELECT
  CAST(NULL AS DATE) AS date,
  CAST(NULL AS INT64) AS account_id,
  CAST(NULL AS INT64) AS campaign_id,
  CAST(NULL AS STRING) AS campaign_name,
  CAST(NULL AS STRING) AS campaign_status,
  CAST(NULL AS STRING) AS metric_basis,
  CAST(NULL AS STRING) AS ad_network_type,
  CAST(NULL AS INT64) AS conversion_action_id,
  CAST(NULL AS STRING) AS conversion_action_resource_name,
  CAST(NULL AS STRING) AS conversion_action_name,
  CAST(NULL AS STRING) AS currency_code,
  CAST(NULL AS STRING) AS attribute_provenance,
  CAST(NULL AS INT64) AS network_impressions,
  CAST(NULL AS INT64) AS network_clicks,
  CAST(NULL AS NUMERIC) AS network_cost,
  CAST(NULL AS FLOAT64) AS network_conversions,
  CAST(NULL AS FLOAT64) AS network_conversions_value,
  CAST(NULL AS FLOAT64) AS network_all_conversions,
  CAST(NULL AS FLOAT64) AS network_all_conversions_value,
  CAST(NULL AS FLOAT64) AS action_conversions,
  CAST(NULL AS FLOAT64) AS action_conversions_value,
  CAST(NULL AS FLOAT64) AS action_all_conversions,
  CAST(NULL AS FLOAT64) AS action_all_conversions_value,
  CAST(NULL AS DATE) AS as_of,
  CAST(NULL AS STRING) AS run_id
LIMIT 0
