-- Publish complete click days as one generation after validation.
-- The non-session query rolls back on an uncaught error.
BEGIN TRANSACTION;

TRUNCATE TABLE `{{ project }}.{{ reporting_dataset }}.performance_campaign`;
INSERT INTO `{{ project }}.{{ reporting_dataset }}.performance_campaign` (
  date,
  account_id,
  campaign_id,
  campaign_name,
  campaign_status,
  metric_basis,
  ad_network_type,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  currency_code,
  attribute_provenance,
  network_impressions,
  network_clicks,
  network_cost,
  network_conversions,
  network_conversions_value,
  network_all_conversions,
  network_all_conversions_value,
  action_conversions,
  action_conversions_value,
  action_all_conversions,
  action_all_conversions_value,
  as_of,
  run_id
)
SELECT
  date,
  account_id,
  campaign_id,
  campaign_name,
  campaign_status,
  metric_basis,
  ad_network_type,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  currency_code,
  attribute_provenance,
  SUM(network_impressions) AS network_impressions,
  SUM(network_clicks) AS network_clicks,
  SUM(network_cost) AS network_cost,
  SUM(network_conversions) AS network_conversions,
  SUM(network_conversions_value) AS network_conversions_value,
  SUM(network_all_conversions) AS network_all_conversions,
  SUM(network_all_conversions_value) AS network_all_conversions_value,
  SUM(action_conversions) AS action_conversions,
  SUM(action_conversions_value) AS action_conversions_value,
  SUM(action_all_conversions) AS action_all_conversions,
  SUM(action_all_conversions_value) AS action_all_conversions_value,
  @as_of AS as_of,
  @run_id AS run_id
FROM `{{ project }}.{{ marts_dataset }}.mart_performance_campaign`
WHERE date BETWEEN
  DATE_SUB(@as_of, INTERVAL {{ reporting_window_days }} DAY)
  AND DATE_SUB(@as_of, INTERVAL 1 DAY)
GROUP BY
  date,
  account_id,
  campaign_id,
  campaign_name,
  campaign_status,
  metric_basis,
  ad_network_type,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  currency_code,
  attribute_provenance;

TRUNCATE TABLE `{{ project }}.{{ reporting_dataset }}.performance_asset_group`;
INSERT INTO `{{ project }}.{{ reporting_dataset }}.performance_asset_group` (
  date,
  account_id,
  campaign_id,
  asset_group_id,
  asset_group_name,
  asset_group_status,
  asset_group_primary_status,
  ad_strength,
  metric_basis,
  ad_network_type,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  currency_code,
  attribute_provenance,
  network_impressions,
  network_clicks,
  network_cost,
  network_conversions,
  network_conversions_value,
  action_conversions,
  action_conversions_value,
  network_all_conversions,
  network_all_conversions_value,
  action_all_conversions,
  action_all_conversions_value,
  as_of,
  run_id
)
SELECT
  date,
  account_id,
  campaign_id,
  asset_group_id,
  asset_group_name,
  asset_group_status,
  asset_group_primary_status,
  ad_strength,
  metric_basis,
  ad_network_type,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  currency_code,
  attribute_provenance,
  SUM(network_impressions) AS network_impressions,
  SUM(network_clicks) AS network_clicks,
  SUM(network_cost) AS network_cost,
  SUM(network_conversions) AS network_conversions,
  SUM(network_conversions_value) AS network_conversions_value,
  SUM(action_conversions) AS action_conversions,
  SUM(action_conversions_value) AS action_conversions_value,
  SUM(network_all_conversions) AS network_all_conversions,
  SUM(network_all_conversions_value) AS network_all_conversions_value,
  SUM(action_all_conversions) AS action_all_conversions,
  SUM(action_all_conversions_value) AS action_all_conversions_value,
  @as_of AS as_of,
  @run_id AS run_id
FROM `{{ project }}.{{ marts_dataset }}.mart_performance_asset_group`
WHERE date BETWEEN
  DATE_SUB(@as_of, INTERVAL {{ reporting_window_days }} DAY)
  AND DATE_SUB(@as_of, INTERVAL 1 DAY)
GROUP BY
  date,
  account_id,
  campaign_id,
  asset_group_id,
  asset_group_name,
  asset_group_status,
  asset_group_primary_status,
  ad_strength,
  metric_basis,
  ad_network_type,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  currency_code,
  attribute_provenance;

TRUNCATE TABLE `{{ project }}.{{ reporting_dataset }}.performance_asset`;
INSERT INTO `{{ project }}.{{ reporting_dataset }}.performance_asset` (
  date,
  account_id,
  campaign_id,
  asset_group_id,
  asset_id,
  metric_basis,
  ad_network_type,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  field_type,
  asset_status,
  asset_primary_status,
  asset_type,
  currency_code,
  attribute_provenance,
  network_impressions,
  network_clicks,
  network_cost,
  network_conversions,
  network_conversions_value,
  action_conversions,
  action_conversions_value,
  network_all_conversions,
  network_all_conversions_value,
  action_all_conversions,
  action_all_conversions_value,
  as_of,
  run_id
)
SELECT
  date,
  account_id,
  campaign_id,
  asset_group_id,
  asset_id,
  metric_basis,
  ad_network_type,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  field_type,
  asset_status,
  asset_primary_status,
  asset_type,
  currency_code,
  attribute_provenance,
  SUM(network_impressions) AS network_impressions,
  SUM(network_clicks) AS network_clicks,
  SUM(network_cost) AS network_cost,
  SUM(network_conversions) AS network_conversions,
  SUM(network_conversions_value) AS network_conversions_value,
  SUM(action_conversions) AS action_conversions,
  SUM(action_conversions_value) AS action_conversions_value,
  SUM(network_all_conversions) AS network_all_conversions,
  SUM(network_all_conversions_value) AS network_all_conversions_value,
  SUM(action_all_conversions) AS action_all_conversions,
  SUM(action_all_conversions_value) AS action_all_conversions_value,
  @as_of AS as_of,
  @run_id AS run_id
FROM `{{ project }}.{{ marts_dataset }}.mart_performance_asset`
WHERE date BETWEEN
  DATE_SUB(@as_of, INTERVAL {{ reporting_window_days }} DAY)
  AND DATE_SUB(@as_of, INTERVAL 1 DAY)
GROUP BY
  date,
  account_id,
  campaign_id,
  asset_group_id,
  asset_id,
  metric_basis,
  ad_network_type,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  field_type,
  asset_status,
  asset_primary_status,
  asset_type,
  currency_code,
  attribute_provenance;

TRUNCATE TABLE `{{ project }}.{{ reporting_dataset }}.asset_performance`;
INSERT INTO `{{ project }}.{{ reporting_dataset }}.asset_performance` (
  date,
  account_id,
  campaign_id,
  asset_group_id,
  asset_id,
  metric_basis,
  ad_network_type,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  field_type,
  asset_status,
  asset_primary_status,
  asset_primary_status_reasons_text,
  asset_name,
  asset_type,
  orientation,
  text,
  image_url,
  image_height_pixels,
  image_width_pixels,
  video_id,
  video_title,
  currency_code,
  attribute_provenance,
  network_impressions,
  network_clicks,
  network_cost,
  network_conversions,
  network_conversions_value,
  action_conversions,
  action_conversions_value,
  network_all_conversions,
  network_all_conversions_value,
  action_all_conversions,
  action_all_conversions_value,
  as_of,
  run_id
)
SELECT
  date,
  account_id,
  campaign_id,
  asset_group_id,
  asset_id,
  metric_basis,
  ad_network_type,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  field_type,
  asset_status,
  asset_primary_status,
  ARRAY_TO_STRING(asset_primary_status_reasons, ', ') AS asset_primary_status_reasons_text,
  asset_name,
  asset_type,
  orientation,
  text,
  image_url,
  image_height_pixels,
  image_width_pixels,
  video_id,
  video_title,
  currency_code,
  attribute_provenance,
  SUM(network_impressions) AS network_impressions,
  SUM(network_clicks) AS network_clicks,
  SUM(network_cost) AS network_cost,
  SUM(network_conversions) AS network_conversions,
  SUM(network_conversions_value) AS network_conversions_value,
  SUM(action_conversions) AS action_conversions,
  SUM(action_conversions_value) AS action_conversions_value,
  SUM(network_all_conversions) AS network_all_conversions,
  SUM(network_all_conversions_value) AS network_all_conversions_value,
  SUM(action_all_conversions) AS action_all_conversions,
  SUM(action_all_conversions_value) AS action_all_conversions_value,
  @as_of AS as_of,
  @run_id AS run_id
FROM `{{ project }}.{{ marts_dataset }}.mart_asset_performance`
WHERE date BETWEEN
  DATE_SUB(@as_of, INTERVAL {{ reporting_window_days }} DAY)
  AND DATE_SUB(@as_of, INTERVAL 1 DAY)
GROUP BY
  date,
  account_id,
  campaign_id,
  asset_group_id,
  asset_id,
  metric_basis,
  ad_network_type,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  field_type,
  asset_status,
  asset_primary_status,
  asset_primary_status_reasons_text,
  asset_name,
  asset_type,
  orientation,
  text,
  image_url,
  image_height_pixels,
  image_width_pixels,
  video_id,
  video_title,
  currency_code,
  attribute_provenance;

TRUNCATE TABLE `{{ project }}.{{ reporting_dataset }}.campaign_truth`;
INSERT INTO `{{ project }}.{{ reporting_dataset }}.campaign_truth` (
  date,
  account_id,
  campaign_id,
  campaign_name,
  campaign_status,
  ad_network_type,
  currency_code,
  attribute_provenance,
  impressions,
  clicks,
  cost,
  conversions,
  conversions_value,
  all_conversions,
  all_conversions_value,
  as_of,
  run_id
)
SELECT
  date,
  account_id,
  campaign_id,
  campaign_name,
  campaign_status,
  ad_network_type,
  currency_code,
  attribute_provenance,
  SUM(impressions) AS impressions,
  SUM(clicks) AS clicks,
  SUM(cost) AS cost,
  SUM(conversions) AS conversions,
  SUM(conversions_value) AS conversions_value,
  SUM(all_conversions) AS all_conversions,
  SUM(all_conversions_value) AS all_conversions_value,
  @as_of AS as_of,
  @run_id AS run_id
FROM `{{ project }}.{{ marts_dataset }}.mart_campaign_truth`
WHERE date BETWEEN
  DATE_SUB(@as_of, INTERVAL {{ reporting_window_days }} DAY)
  AND DATE_SUB(@as_of, INTERVAL 1 DAY)
GROUP BY
  date,
  account_id,
  campaign_id,
  campaign_name,
  campaign_status,
  ad_network_type,
  currency_code,
  attribute_provenance;

TRUNCATE TABLE `{{ project }}.{{ reporting_dataset }}.cohort_campaign`;
INSERT INTO `{{ project }}.{{ reporting_dataset }}.cohort_campaign` (
  click_date,
  account_id,
  campaign_id,
  ad_network_type,
  metric_basis,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  cohort_day,
  is_window_rung,
  cohort_label,
  window_days,
  window_provenance,
  provenance,
  unavailable_reason,
  maturity,
  observed_through,
  click_day_cost,
  cohorted_conversions,
  cohorted_value,
  unknown_lag_conversions,
  unknown_lag_value,
  stale_cell_count,
  missing_cost_cell_count,
  as_of,
  run_id,
  cohort_counting
)
SELECT
  click_date,
  account_id,
  campaign_id,
  ad_network_type,
  metric_basis,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  cohort_day,
  is_window_rung,
  cohort_label,
  window_days,
  window_provenance,
  provenance,
  unavailable_reason,
  maturity,
  observed_through,
  SUM(click_day_cost) AS click_day_cost,
  SUM(cohorted_conversions) AS cohorted_conversions,
  SUM(cohorted_value) AS cohorted_value,
  SUM(unknown_lag_conversions) AS unknown_lag_conversions,
  SUM(unknown_lag_value) AS unknown_lag_value,
  SUM(stale_cell_count) AS stale_cell_count,
  SUM(missing_cost_cell_count) AS missing_cost_cell_count,
  @as_of AS as_of,
  @run_id AS run_id,
  cohort_counting
FROM `{{ project }}.{{ marts_dataset }}.mart_cohort_campaign`
WHERE click_date BETWEEN
  DATE_SUB(@as_of, INTERVAL {{ reporting_window_days }} DAY)
  AND DATE_SUB(@as_of, INTERVAL 1 DAY)
  AND click_day_cost IS NOT NULL
  AND cohort_day <= LEAST(window_days, {{ reporting_window_days }})
  AND (
    cohort_day IN ({{ cohort_days | join(', ') }})
    OR (is_window_rung
      AND cohort_day = LEAST(window_days, {{ reporting_window_days }}))
  )
  AND cohort_day > 0
GROUP BY
  click_date,
  account_id,
  campaign_id,
  ad_network_type,
  metric_basis,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  cohort_day,
  is_window_rung,
  cohort_label,
  window_days,
  window_provenance,
  provenance,
  unavailable_reason,
  maturity,
  observed_through,
  cohort_counting;

TRUNCATE TABLE `{{ project }}.{{ reporting_dataset }}.cohort_asset_group`;
INSERT INTO `{{ project }}.{{ reporting_dataset }}.cohort_asset_group` (
  click_date,
  account_id,
  campaign_id,
  asset_group_id,
  ad_network_type,
  metric_basis,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  cohort_day,
  is_window_rung,
  cohort_label,
  window_days,
  window_provenance,
  provenance,
  unavailable_reason,
  maturity,
  observed_through,
  click_day_cost,
  cohorted_conversions,
  cohorted_value,
  unknown_lag_conversions,
  unknown_lag_value,
  stale_cell_count,
  missing_cost_cell_count,
  as_of,
  run_id,
  cohort_counting
)
SELECT
  click_date,
  account_id,
  campaign_id,
  asset_group_id,
  ad_network_type,
  metric_basis,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  cohort_day,
  is_window_rung,
  cohort_label,
  window_days,
  window_provenance,
  provenance,
  unavailable_reason,
  maturity,
  observed_through,
  SUM(click_day_cost) AS click_day_cost,
  SUM(cohorted_conversions) AS cohorted_conversions,
  SUM(cohorted_value) AS cohorted_value,
  SUM(unknown_lag_conversions) AS unknown_lag_conversions,
  SUM(unknown_lag_value) AS unknown_lag_value,
  SUM(stale_cell_count) AS stale_cell_count,
  SUM(missing_cost_cell_count) AS missing_cost_cell_count,
  @as_of AS as_of,
  @run_id AS run_id,
  cohort_counting
FROM `{{ project }}.{{ marts_dataset }}.mart_cohort_asset_group`
WHERE click_date BETWEEN
  DATE_SUB(@as_of, INTERVAL {{ reporting_window_days }} DAY)
  AND DATE_SUB(@as_of, INTERVAL 1 DAY)
  AND click_day_cost IS NOT NULL
  AND cohort_day <= LEAST(window_days, {{ reporting_window_days }})
  AND (
    cohort_day IN ({{ cohort_days | join(', ') }})
    OR (is_window_rung
      AND cohort_day = LEAST(window_days, {{ reporting_window_days }}))
  )
  AND cohort_day > 0
GROUP BY
  click_date,
  account_id,
  campaign_id,
  asset_group_id,
  ad_network_type,
  metric_basis,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  cohort_day,
  is_window_rung,
  cohort_label,
  window_days,
  window_provenance,
  provenance,
  unavailable_reason,
  maturity,
  observed_through,
  cohort_counting;

TRUNCATE TABLE `{{ project }}.{{ reporting_dataset }}.cohort_asset`;
INSERT INTO `{{ project }}.{{ reporting_dataset }}.cohort_asset` (
  click_date,
  account_id,
  campaign_id,
  asset_group_id,
  asset_id,
  field_type,
  ad_network_type,
  metric_basis,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  cohort_day,
  is_window_rung,
  cohort_label,
  window_days,
  window_provenance,
  provenance,
  unavailable_reason,
  maturity,
  observed_through,
  click_day_cost,
  cohorted_conversions,
  cohorted_value,
  unknown_lag_conversions,
  unknown_lag_value,
  stale_cell_count,
  missing_cost_cell_count,
  as_of,
  run_id,
  cohort_counting
)
SELECT
  click_date,
  account_id,
  campaign_id,
  asset_group_id,
  asset_id,
  field_type,
  ad_network_type,
  metric_basis,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  cohort_day,
  is_window_rung,
  cohort_label,
  window_days,
  window_provenance,
  provenance,
  unavailable_reason,
  maturity,
  observed_through,
  SUM(click_day_cost) AS click_day_cost,
  SUM(cohorted_conversions) AS cohorted_conversions,
  SUM(cohorted_value) AS cohorted_value,
  SUM(unknown_lag_conversions) AS unknown_lag_conversions,
  SUM(unknown_lag_value) AS unknown_lag_value,
  SUM(stale_cell_count) AS stale_cell_count,
  SUM(missing_cost_cell_count) AS missing_cost_cell_count,
  @as_of AS as_of,
  @run_id AS run_id,
  cohort_counting
FROM `{{ project }}.{{ marts_dataset }}.mart_cohort_asset`
WHERE click_date BETWEEN
  DATE_SUB(@as_of, INTERVAL {{ reporting_window_days }} DAY)
  AND DATE_SUB(@as_of, INTERVAL 1 DAY)
  AND click_day_cost IS NOT NULL
  AND cohort_day <= LEAST(window_days, {{ reporting_window_days }})
  AND (
    cohort_day IN ({{ cohort_days | join(', ') }})
    OR (is_window_rung
      AND cohort_day = LEAST(window_days, {{ reporting_window_days }}))
  )
GROUP BY
  click_date,
  account_id,
  campaign_id,
  asset_group_id,
  asset_id,
  field_type,
  ad_network_type,
  metric_basis,
  conversion_action_id,
  conversion_action_resource_name,
  conversion_action_name,
  cohort_day,
  is_window_rung,
  cohort_label,
  window_days,
  window_provenance,
  provenance,
  unavailable_reason,
  maturity,
  observed_through,
  cohort_counting;

COMMIT TRANSACTION;
